# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/centos-6.6-64-puppet"
  config.vm.box_check_update = true
  
  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 8080
    
    web.vm.network "private_network", ip: "172.31.22.173"
    
    web.vm.provider "virtualbox" do |vb|
      #   # Display the VirtualBox GUI when booting the machine
      #   vb.gui = true
      #
      #   # Customize the amount of memory on the VM:
      #   vb.memory = "6144"
    end
    
    web.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.manifests_path = "vagrant-manifests"
      puppet.manifest_file = "web.pp"
      puppet.hiera_config_path = "hiera.yaml"
    end
    
  end

  config.vm.define "build" do |build|
    build.vm.network "forwarded_port", guest: 8080, host: 8081
    
    build.vm.network "private_network", ip: "192.168.1.96"
    
    build.vm.provider "virtualbox" do |vb|
      #   # Display the VirtualBox GUI when booting the machine
      #   vb.gui = true
      #
      #   # Customize the amount of memory on the VM:
      #   vb.memory = "6144"
    end
    
    build.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.manifests_path = "vagrant-manifests"
      puppet.manifest_file = "build.pp"
      puppet.hiera_config_path = "hiera.yaml"
    end
    
  end

  
  config.vm.define "app" do |app|
    app.vm.network "forwarded_port", guest: 8080, host: 8082
    
    
    app.vm.network "private_network", ip: "172.31.58.65"
    
    app.vm.provider "virtualbox" do |vb|
      #   # Display the VirtualBox GUI when booting the machine
      #   vb.gui = true
      #
      #   # Customize the amount of memory on the VM:
      #   vb.memory = "6144"
    end
    
    app.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"
      puppet.manifests_path = "vagrant-manifests"
      puppet.manifest_file = "app.pp"
      puppet.hiera_config_path = "hiera.yaml"
    end
    
  end
  
  
end

